<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            'PHP',
            'Laravel',
            'JavaScript',
            'Vue.js',
            'React.js',
            'Angular',
            'Node.js',
            'Python',
            'Django',
            'Flask',
            'Ruby',
            'Rails',
            'Java',
            'Spring',
            'Kotlin',
            'Android',
            'Swift',
            'iOS',
            'Go',
            'Rust',
            'Dart',
            'Flutter',
            'C#',
            'ASP.NET',
            'SQL',
            'NoSQL',
            'MongoDB',
            'Firebase',
            'Docker',
            'Kubernetes',
            'AWS',
            'Azure',
            'GCP',
            'CI/CD',
            'DevOps',
            'TDD',
            'BDD',
            'Agile',
            'Scrum',
            'Kanban',
            'XP',
            'Lean',
            'Design Patterns',
            'Refactoring',
            'Clean Code',
            'SOLID',
            'RESTful',
            'GraphQL',
            'OAuth',
            'JWT',
            'WebSockets',
            'PWA',
            'AMP',
            'SEO',
            'Performance',
            'Security',
            'Testing',
            'Automation',
            'Monitoring',
            'Logging',
            'Analytics',
            'Big Data',
            'Machine Learning',
            'AI',
            'Blockchain',
            'Cryptocurrency',
            'NFT',
            'Metaverse',
            'AR',
            'VR',
            'Game Development',
            'Unity',
            'Unreal Engine',
            '2D',
            '3D',
            'Pixel Art',
            'UI/UX',
            'Responsive Design',
            'Mobile First',
            'Accessibility',
            'Dark Mode',
            'Microservices',
            'Serverless',
            'Jamstack',
            'Headless',
            'CMS',
            'eCommerce',
            'SaaS',
            'PaaS',
            'IaaS',
            'FaaS',
            'BaaS',
            'API',
            'Webhooks',
            'WebSockets',
            'GraphQL',
            'OAuth',
            'JWT',
            'WebSockets',
            'PWA',
            'AMP',
            'SEO',
            'Performance',
            'Security',
            'Testing',
            'Automation',
            'Monitoring',
            'Logging',
        ];

        foreach ($categories as $category) {
            Category::create([
                'name' => $category,
            ]);
        }
    }
}
